// Copyright (c) 2026 Holley Studios. All rights reserved.
/**
 * Thesmos adapter system — generates AI assistant instruction files
 * from a shared canonical rule registry. All generator functions are pure.
 *
 * Supported targets and their output paths:
 *   gemini  → GEMINI.md
 *   claude  → CLAUDE.md
 *   cursor  → .cursor/rules/thesmos.mdc
 *   copilot → .github/copilot-instructions.md
 *   codex   → .codex/thesmos.md
 *   agents  → AGENTS.md
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { ThesmosConfig, Severity } from './types';
import { injectGeneratedSection } from './output';
import { SEVERITY_EMOJI, SEVERITY_ORDER } from './severity';
import { generateContextCapsule, saveContextCapsule } from './context-capsule.js';
export { THESMOS_RULES } from './rules/registry';

// ── Types ─────────────────────────────────────────────────────────────────────

export type AdapterTarget =
  | 'gemini'
  | 'claude'
  | 'cursor'
  | 'copilot'
  | 'codex'
  | 'agents';

export interface Rule {
  id: string;
  category: string;
  description: string;
  severity: Severity;
  tags: string[];
  example?: string;
}

export interface AdapterManifest {
  target: AdapterTarget;
  outputPath: string;
  generated: boolean;
}

// ── Output paths ──────────────────────────────────────────────────────────────

export const ADAPTER_OUTPUT_PATHS: Record<AdapterTarget, string> = {
  gemini: 'GEMINI.md',
  claude: 'CLAUDE.md',
  cursor: '.cursor/rules/thesmos.mdc',
  copilot: '.github/copilot-instructions.md',
  codex: '.codex/thesmos.md',
  agents: 'AGENTS.md',
};

// ── Filter helpers (pure) ─────────────────────────────────────────────────────

export function getRulesByTag(rules: Rule[], tag: string): Rule[] {
  return rules.filter((r) => r.tags.includes(tag));
}

export function getRulesBySeverity(rules: Rule[], severity: Severity): Rule[] {
  return rules.filter((r) => r.severity === severity);
}

export function getRulesByCategory(rules: Rule[], categories: string[]): Rule[] {
  const set = new Set(categories);
  return rules.filter((r) => set.has(r.category));
}

// ── Shared formatting (pure) ──────────────────────────────────────────────────

function formatRulesSections(rules: Rule[]): string {
  const grouped = new Map<Severity, Rule[]>();
  for (const sev of SEVERITY_ORDER) grouped.set(sev, []);
  for (const rule of rules) grouped.get(rule.severity)!.push(rule);

  let md = '';
  for (const sev of SEVERITY_ORDER) {
    const group = grouped.get(sev)!;
    if (group.length === 0) continue;
    md += `\n### ${SEVERITY_EMOJI[sev]} ${sev}\n\n`;
    for (const rule of group) {
      md += `**[${rule.id}]** ${rule.description}\n`;
      if (rule.example) {
        md += `\n\`\`\`ts\n${rule.example}\n\`\`\`\n`;
      }
      md += '\n';
    }
  }
  return md.trimEnd();
}

// ── Per-target generators (pure) ──────────────────────────────────────────────

export function generateGeminiRules(rules: Rule[], config: ThesmosConfig): string {
  return [
    `_Generated by Thesmos ${config.version} for **${config.project}**._`,
    '',
    'The following rules are enforced during code review. Violations marked **BLOCKER** must be fixed before merge.',
    formatRulesSections(rules),
  ].join('\n');
}

/**
 * Claude adapter produces a compact reference table instead of full rule dumps.
 * Full descriptions live in .thesmos/governance/CODE_REVIEW.md.
 * This keeps CLAUDE.md thin and prevents drift between the file and the canonical source.
 */
function generatePantheonProtocol(): string {
  return `
## Thesmos Pantheon — Universal Intelligence Protocol

All 40 God Agents (Zeus, Athena, Apollo, Hermes, Argus, etc.) operate with this protocol.
Agents active in this repo are listed in the **Active Thesmos Context** section with their invocation.

### Consultation Mode
When asked "what should we do?" or "is this right?": present 2–3 ranked options.
Format:
**Recommended:** [Option A] — [trade-off] · [ASSUMPTION: X]
**Alternative:** [Option B] — [trade-off] · [ASSUMPTION: Y]
**Also consider:** [Option C] — only if [condition]

### Calibrated Confidence
- No marker = validated by framework or evidence
- [LIKELY] = strong inference, not yet confirmed in this context
- [ASSUMPTION] = this must be true for the recommendation to hold; verify before shipping
- [VERIFY] = specific fact or code detail to confirm before acting

### Adversarial Self-Check
Before any significant recommendation, surface:
1. Strongest counterargument to this recommendation
2. The one assumption that, if wrong, flips everything
3. What domain this touches outside your specialty (and which God Agent to flag)
4. The cheapest way to test this before committing

### Governance Badge
Every God Agent delivery closes with:
> **Thesmos check:** [RULE_ID] ✅ | [RULE_ID] ✅ | [any findings flagged]

### Proactive Insight Protocol
After completing a task, if you noticed something you weren't asked about:
> **⚡ While working on this:** [finding] — [severity] — [suggested God Agent to address it]

### Temporal Scope
Strategic recommendations include: "Revisit if: [specific condition]" or "Valid for: [timeframe]"

### God Council Escalation
Trigger when: two agents conflict, decision is irreversible, BLOCKER finding spans domains, or explicit escalation.
Escalate to: **God Agent Zeus** for arbitration. Zeus decides; all agents execute.

### Problem Diagnosis First
Before solving: "Is this the stated problem or the real problem?"
Ask the diagnostic question before the answer.`.trimStart();
}

export function generateClaudeRules(rules: Rule[], config: ThesmosConfig): string {
  // Only BLOCKER and HIGH are embedded inline — MEDIUM/LOW/TECH_DEBT live in .thesmos/RULES.md.
  // Embedding all severities causes context thrashing: 450+ rules × 3 columns = 1150+ lines
  // loaded on every turn. MEDIUM/LOW rules are advisory; agents can pull them on demand.
  const CLAUDE_SEVERITIES: Severity[] = ['BLOCKER', 'HIGH'];
  const grouped = new Map<Severity, Rule[]>();
  for (const sev of CLAUDE_SEVERITIES) grouped.set(sev, []);
  for (const rule of rules) {
    if (CLAUDE_SEVERITIES.includes(rule.severity)) {
      grouped.get(rule.severity)!.push(rule);
    }
  }

  const parts: string[] = [
    `_Generated by Thesmos ${config.version} for **${config.project}**. Full rule details in \`.thesmos/governance/CODE_REVIEW.md\`._`,
    '',
    '## Enforced Rules',
    '',
    '> **BLOCKER and HIGH only.** MEDIUM / LOW / TECH_DEBT rules are in `.thesmos/RULES.md` — not embedded here to prevent context thrashing.',
    '',
  ];

  for (const sev of CLAUDE_SEVERITIES) {
    const group = grouped.get(sev)!;
    if (group.length === 0) continue;
    parts.push(`### ${SEVERITY_EMOJI[sev]} ${sev}`, '');
    parts.push('| Rule | Category | Summary |');
    parts.push('|---|---|---|');
    for (const rule of group) {
      // Truncate description to keep the table scannable; full text is in CODE_REVIEW.md
      const summary = rule.description.length > 80
        ? rule.description.slice(0, 77) + '…'
        : rule.description;
      parts.push(`| [${rule.id}] | \`${rule.category}\` | ${summary} |`);
    }
    parts.push('');
  }

  parts.push(
    `_Run \`npm run thesmos:review\` for findings. Run \`npm run thesmos:validate\` to gate CI._`
  );

  parts.push('', generatePantheonProtocol());

  return parts.join('\n').trimEnd();
}

export function generateCursorRules(rules: Rule[], config: ThesmosConfig): string {
  return [
    `_Generated by Thesmos ${config.version} for **${config.project}**._`,
    '',
    'These rules apply to all code suggestions. Reject or flag any code that violates a BLOCKER or HIGH rule.',
    formatRulesSections(rules),
  ].join('\n');
}

export function generateCopilotRules(rules: Rule[], config: ThesmosConfig): string {
  return [
    `_Generated by Thesmos ${config.version} for **${config.project}**._`,
    '',
    'When suggesting completions or reviewing code, enforce the following rules. Never suggest code that violates a BLOCKER rule.',
    formatRulesSections(rules),
  ].join('\n');
}

export function generateCodexRules(rules: Rule[], config: ThesmosConfig): string {
  return [
    `_Generated by Thesmos ${config.version} for **${config.project}**._`,
    '',
    'All generated code must comply with the following rules. Stop and report any BLOCKER violation before proceeding.',
    formatRulesSections(rules),
  ].join('\n');
}

export function generateAgentsRules(rules: Rule[], config: ThesmosConfig): string {
  const blockers = getRulesBySeverity(rules, 'BLOCKER');
  const highs = getRulesBySeverity(rules, 'HIGH');
  const rest = rules.filter((r) => r.severity !== 'BLOCKER' && r.severity !== 'HIGH');

  const parts: string[] = [
    `_Generated by Thesmos ${config.version} for **${config.project}**._`,
    '',
  ];

  if (blockers.length > 0) {
    parts.push('**CRITICAL — These rules must never be violated. Stop and report before proceeding.**', '');
    for (const rule of blockers) {
      parts.push(`- **[${rule.id}]** ${rule.description}`);
    }
    parts.push('');
  }

  if (highs.length > 0) {
    parts.push('**HIGH PRIORITY — Must fix before task completion.**', '');
    for (const rule of highs) {
      parts.push(`- **[${rule.id}]** ${rule.description}`);
    }
    parts.push('');
  }

  if (rest.length > 0) {
    parts.push('**GUIDELINES**', '');
    for (const rule of rest) {
      parts.push(`- **[${rule.id}]** (${rule.severity}) ${rule.description}`);
    }
  }

  return parts.join('\n').trimEnd();
}

// ── Dispatch tables ───────────────────────────────────────────────────────────

const RULE_GENERATORS: Record<
  AdapterTarget,
  (rules: Rule[], config: ThesmosConfig) => string
> = {
  gemini: generateGeminiRules,
  claude: generateClaudeRules,
  cursor: generateCursorRules,
  copilot: generateCopilotRules,
  codex: generateCodexRules,
  agents: generateAgentsRules,
};

const ADAPTER_PREAMBLES: Record<AdapterTarget, (config: ThesmosConfig) => string> = {
  gemini: (c) =>
    `# ${c.project} — Gemini Code Assist\n\n_Add project-specific context above the generated section._`,

  claude: (c) => [
    `# ${c.project} — Claude Code Instructions`,
    '',
    '> This file is a thin adapter over Thesmos. All canonical rules, playbooks, and governance',
    '> live in `.thesmos/`. Do not edit the generated section — run `npm run thesmos:adapters` to refresh it.',
    '',
    '## Before Each Task',
    '',
    '1. Read `.thesmos/context.md` for current stack, established patterns, and active constraints.',
    '2. Read `.thesmos/README.md` for project architecture and current state.',
    '3. Treat `.thesmos/GUARDRAILS.md` as mandatory — these constraints cannot be overridden.',
    '4. Check `.thesmos/report.json` for current repo intelligence (routes, API auth gaps, large files, boundary risks).',
    '5. For code review behavior, follow `.thesmos/governance/CODE_REVIEW.md`.',
    '6. For AI review expectations, follow `.thesmos/governance/REVIEW_AGENT.md`.',
    '7. Before creating pages, components, API routes, refactors, or build fixes, consult `.thesmos/playbooks/`.',
    '',
    '## Behavioral Rules',
    '',
    '8. Never bypass severity rules — BLOCKER findings must be addressed before continuing.',
    '9. Never overwrite content outside `<!-- THESMOS:GENERATED START … -->` / `<!-- THESMOS:GENERATED END … -->` markers.',
    '10. Prefer small, reversible, tested changes.',
    `11. After changes, run the relevant Thesmos command (\`npm run thesmos:scan\`, \`thesmos:review\`, \`thesmos:validate\`, or \`thesmos:doctor\`).`,
    '12. End each task by listing changed files and test results.',
    '',
    '_Add project-specific context above the generated section._',
  ].join('\n'),

  cursor: (c) =>
    `---\ndescription: Thesmos code governance rules for ${c.project}\nalwaysApply: true\n---\n\n_Add project-specific rules above the generated section._`,
  copilot: (c) =>
    `# Copilot Instructions — ${c.project}\n\n_Add project-specific context above the generated section._`,
  codex: (c) =>
    `# ${c.project} — Codex Instructions\n\n_Add project-specific context above the generated section._`,
  agents: (c) =>
    `# AGENTS — ${c.project}\n\n_Add project-specific agent instructions above the generated section._`,
};

// ── Adapter metadata ──────────────────────────────────────────────────────────

/** Metadata embedded inside every generated adapter section. No timestamps. */
export interface AdapterMeta {
  version: string;
  target: AdapterTarget;
  ruleCount: number;
}

/** Minimal catalog context passed to adapter builders — avoids importing catalog.ts. */
export interface AdapterCatalogEntry {
  id: string;
  name: string;
}

export interface AdapterCatalog {
  agents: AdapterCatalogEntry[];
  skills: AdapterCatalogEntry[];
  profile?: string;
}

function formatCatalogContext(catalog: AdapterCatalog): string {
  if (catalog.agents.length === 0 && catalog.skills.length === 0 && !catalog.profile) return '';
  const lines: string[] = ['', '---', '', '## Active Thesmos Context', ''];
  if (catalog.profile) lines.push(`**Profile:** \`${catalog.profile}\``, '');
  if (catalog.agents.length > 0) {
    lines.push('**Active Agents:**', '');
    for (const a of catalog.agents) lines.push(`- **${a.name}** (\`${a.id}\`) — Invoke: \`Agent({ subagent_type: "${a.id}", prompt: "..." })\``);
    lines.push('');
  }
  if (catalog.skills.length > 0) {
    lines.push('**Active Skills:**', '');
    for (const s of catalog.skills) lines.push(`- **[${s.id}]** ${s.name}`);
    lines.push('');
  }
  lines.push('_Run `thesmos catalog:list` to see all available agents and skills._');
  return lines.join('\n');
}

/**
 * Parse the THESMOS:META comment from an adapter file.
 * Returns null when the comment is absent or malformed.
 */
export function parseAdapterMeta(content: string): AdapterMeta | null {
  const match = content.match(/<!--\s*THESMOS:META\s+(\{[^}]+\})\s*-->/);
  if (!match || !match[1]) return null;
  try {
    return JSON.parse(match[1]) as AdapterMeta;
  } catch {
    return null;
  }
}

/**
 * Returns whether an adapter file's embedded metadata is current.
 * Freshness is checked by ruleCount and version only — no timestamps.
 */
export function isAdapterFresh(
  content: string,
  rules: Rule[],
  config: ThesmosConfig
): { fresh: boolean; reason: string } {
  const meta = parseAdapterMeta(content);
  if (!meta) {
    return { fresh: false, reason: 'no metadata — run thesmos adapters to refresh' };
  }
  if (meta.ruleCount !== rules.length) {
    return {
      fresh: false,
      reason: `rule count mismatch: file has ${meta.ruleCount}, registry has ${rules.length}`,
    };
  }
  if (meta.version !== config.version) {
    return {
      fresh: false,
      reason: `version mismatch: file has ${meta.version}, current is ${config.version}`,
    };
  }
  return { fresh: true, reason: 'up to date' };
}

// ── Public pure merger ────────────────────────────────────────────────────────

/**
 * Merges a freshly generated rules section into an existing adapter document.
 * If the document is empty, uses the target-specific preamble as the base.
 * Idempotent: calling twice with identical input produces identical output.
 *
 * The generated section always begins with a THESMOS:META comment so that
 * isAdapterFresh() can verify the file without re-running the generator.
 */
export function buildAdapterContent(
  target: AdapterTarget,
  existing: string,
  rules: Rule[],
  config: ThesmosConfig,
  catalog?: AdapterCatalog
): string {
  const base =
    existing.trim() === '' ? ADAPTER_PREAMBLES[target](config) : existing;
  const meta: AdapterMeta = { version: config.version, target, ruleCount: rules.length };
  const metaComment = `<!-- THESMOS:META ${JSON.stringify(meta)} -->`;
  const catalogCtx = catalog ? formatCatalogContext(catalog) : '';
  const generated = `${metaComment}\n${RULE_GENERATORS[target](rules, config)}${catalogCtx}`;
  return injectGeneratedSection(base, 'rules', generated);
}

// ── I/O orchestrator ──────────────────────────────────────────────────────────

/**
 * Writes adapter files for the requested targets under `root`.
 * Existing files are updated in-place (generated section only);
 * manually written content outside the markers is preserved.
 */
export function writeAllAdapters(
  root: string,
  rules: Rule[],
  config: ThesmosConfig,
  targets: AdapterTarget[] = [
    'gemini',
    'claude',
    'cursor',
    'copilot',
    'codex',
    'agents',
  ],
  catalog?: AdapterCatalog
): AdapterManifest[] {
  // Auto-generate context snapshot alongside adapters so CLAUDE.md step 1 always has fresh data
  try {
    const capsule = generateContextCapsule(root);
    saveContextCapsule(root, capsule);
  } catch { /* non-fatal — context snapshot is advisory */ }

  return targets.map((target) => {
    const relPath = ADAPTER_OUTPUT_PATHS[target];
    const absPath = join(root, relPath);
    const existing = existsSync(absPath) ? readFileSync(absPath, 'utf8') : '';
    const content = buildAdapterContent(target, existing, rules, config, catalog);
    const dir = dirname(absPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(absPath, content, 'utf8');
    return { target, outputPath: relPath, generated: true };
  });
}
