// Copyright (c) 2026 Holley Studios. All rights reserved.
/**
 * Automation generator — creates CI/CD automation from wizard answers.
 *
 * Outputs (scaffold mode):
 *   - .github/workflows/<name>.yml   (cron/webhook/push triggers)
 *   - OR .thesmos/automation/<name>.sh  (file-change / manual triggers)
 */

import type { WizardAnswers, WizardContext } from '../wizard.js';
import { makeLogger } from '../../logger.js';

const log = makeLogger('generator:automation');

export interface AutomationArtifact {
  files: Array<{ path: string; content: string; label: string }>;
  automationName: string;
}

// ── GitHub Actions workflow ────────────────────────────────────────────────────

function buildAutomationWorkflow(answers: WizardAnswers, context: WizardContext): string {
  const name = answers['name'] ?? 'automation';
  const displayName = name.split('-').map((w: string) => w[0]!.toUpperCase() + w.slice(1)).join(' ');
  const job = answers['job'] ?? 'automated task';
  const trigger = answers['trigger'] ?? 'manual';
  const steps = answers['steps'] ?? 'run tests';
  const onFailure = answers['onFailure'] ?? 'fail and alert';
  const needsApproval = answers['needsApproval'] ?? 'no';
  const stack = context.detectedStack.join(', ') || 'unknown';

  const triggerYaml = {
    cron: `on:\n  schedule:\n    - cron: '0 6 * * 1'  # Every Monday 6am UTC\n  workflow_dispatch:  # Allow manual trigger`,
    webhook: `on:\n  repository_dispatch:\n    types: [${name}-trigger]\n  workflow_dispatch:`,
    'file-change': `on:\n  push:\n    paths:\n      - '**/*.ts'\n      - '**/*.js'\n      - 'package.json'`,
    manual: `on:\n  workflow_dispatch:\n    inputs:\n      dry_run:\n        description: 'Dry run (no side effects)'\n        type: boolean\n        default: true`,
    event: `on:\n  push:\n    branches: [main]\n  pull_request:`,
  }[trigger] ?? `on:\n  workflow_dispatch:`;

  const approvalStep = needsApproval === 'yes'
    ? `
      - name: Await approval
        uses: trstringer/manual-approval@v1
        with:
          secret: \${{ github.TOKEN }}
          approvers: \${{ github.repository_owner }}
          minimum-approvals: 1
` : '';

  const mainSteps = {
    'run-tests': `
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Thesmos governance scan
        run: npx thesmos review`,
    'build-artifact': `
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${name}-build
          path: dist/`,
    deploy: `
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          # TODO: add deployment command
          echo "Deploying ${displayName}..."`,
    'send-notification': `
      - name: Send notification
        run: |
          # TODO: replace with real notification command (Slack, email, etc.)
          echo "Notification: ${displayName} completed"`,
    custom: `
      - name: ${displayName}
        run: |
          # TODO: implement ${job}
          echo "Running ${displayName}..."`,
  }[steps] ?? `
      - name: ${displayName}
        run: echo "Running ${job}..."`;

  const onFailureConfig = {
    'fail-alert': `    continue-on-error: false`,
    'retry-alert': `    continue-on-error: false\n    # Retry handled by GitHub Actions retry mechanism`,
    'log-continue': `    continue-on-error: true`,
  }[onFailure.replace(/\s/g, '-')] ?? '';

  return `# ${displayName}
# ${job}
# Generated by thesmos build:automation
# Stack: ${stack}

name: ${displayName}

${triggerYaml}

jobs:
  ${name}:
    name: ${displayName}
    runs-on: ubuntu-latest
    timeout-minutes: 30
${onFailureConfig ? `    ${onFailureConfig}` : ''}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
${approvalStep}${mainSteps}
`;
}

// ── Shell script (for file-change / manual local automations) ─────────────────

function buildShellScript(answers: WizardAnswers): string {
  const name = answers['name'] ?? 'automation';
  const job = answers['job'] ?? 'automated task';
  const steps = answers['steps'] ?? 'run tests';
  const onFailure = answers['onFailure'] ?? 'fail and alert';

  const failureHandling = onFailure === 'retry-alert'
    ? `
run_with_retry() {
  local max=3
  local count=0
  until "$@" || [ $count -ge $max ]; do
    count=$((count + 1))
    echo "[${name}] Attempt $count failed. Retrying in 5s..."
    sleep 5
  done
  if [ $count -ge $max ]; then
    echo "[${name}] ERROR: All $max attempts failed"
    exit 1
  fi
}`
    : '';

  return `#!/usr/bin/env bash
# ${name} — ${job}
# Generated by thesmos build:automation
# Run: bash .thesmos/automation/${name}.sh [--dry-run]

set -euo pipefail

DRY_RUN=false
for arg in "$@"; do
  [ "$arg" = "--dry-run" ] && DRY_RUN=true
done
${failureHandling}

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [${name}] $*"; }
error() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [${name}] ERROR: $*" >&2; }

log "Starting ${displayName(name)}"
[ "$DRY_RUN" = true ] && log "DRY RUN — no side effects will be applied"

# TODO: implement ${job}
${steps === 'run-tests' ? 'npm test' : steps === 'build-artifact' ? 'npm run build' : `echo "Running: ${job}"`}

log "Completed successfully"
`;
}

function displayName(name: string): string {
  return name.split('-').map((w) => w[0]!.toUpperCase() + w.slice(1)).join(' ');
}

// ── Plan generator ────────────────────────────────────────────────────────────

export function generateAutomationPlan(answers: WizardAnswers, context: WizardContext): string {
  const name = answers['name'] ?? 'automation';
  const dn = displayName(name);
  const job = answers['job'] ?? 'automated task';
  const trigger = answers['trigger'] ?? 'manual';
  const steps = answers['steps'] ?? 'run tests';
  const onFailure = answers['onFailure'] ?? 'fail and alert';
  const needsApproval = answers['needsApproval'] ?? 'no';

  const outputFile = trigger === 'file-change' || trigger === 'manual'
    ? `.thesmos/automation/${name}.sh`
    : `.github/workflows/${name}.yml`;

  return [
    `# ${dn} — Automation Implementation Plan`,
    '',
    `## Purpose`,
    job,
    '',
    `## Architecture decisions`,
    '',
    `| Decision | Choice | Rationale |`,
    `|----------|--------|-----------|`,
    `| Trigger | ${trigger} | When this automation runs |`,
    `| Steps | ${steps} | What the automation does |`,
    `| On failure | ${onFailure} | Recovery behavior |`,
    `| Needs approval | ${needsApproval} | Human gate requirement |`,
    '',
    `## Output file`,
    '',
    `\`${outputFile}\``,
    '',
    `## Implementation checklist`,
    '',
    `- [ ] Create \`${outputFile}\``,
    needsApproval === 'yes' ? `- [ ] Configure approval reviewers` : '',
    `- [ ] Test trigger: ${trigger === 'cron' ? 'wait for scheduled run or use workflow_dispatch' : trigger}`,
    `- [ ] Verify failure handling: ${onFailure}`,
    `- [ ] Run Thesmos scan on generated files`,
    '',
    `## Security considerations`,
    '',
    `- Secrets are injected via GitHub Secrets or env vars, never hardcoded`,
    `- Automation runs with minimal permissions (read by default)`,
    needsApproval === 'yes' ? `- Manual approval gate prevents unauthorized execution` : '',
    `- Log all actions and outcomes for audit trail`,
    '',
    `---`,
    `*Generated by thesmos build:automation --plan*`,
    `*Run: thesmos build:automation --scaffold to write the automation file*`,
  ].filter((l) => l !== '').join('\n');
}

// ── Main generator ────────────────────────────────────────────────────────────

export async function generateAutomation(
  answers: WizardAnswers,
  context: WizardContext,
  opts: { scaffold: boolean; planOnly: boolean },
): Promise<AutomationArtifact> {
  const name = (answers['name'] ?? 'automation').toLowerCase().replace(/[^a-z0-9-]/g, '-');
  answers['name'] = name;
  const trigger = answers['trigger'] ?? 'manual';

  const files: AutomationArtifact['files'] = [];

  if (opts.scaffold) {
    if (trigger === 'file-change' || trigger === 'manual') {
      files.push({
        path: `.thesmos/automation/${name}.sh`,
        content: buildShellScript(answers),
        label: 'Shell automation script',
      });
    } else {
      files.push({
        path: `.github/workflows/${name}.yml`,
        content: buildAutomationWorkflow(answers, context),
        label: 'GitHub Actions automation workflow',
      });
    }
  }

  log.info('automation generator complete', { name, files: files.length });
  return { files, automationName: name };
}
